---
- name: Kiểm tra kết nối SSH và lấy cấu hình từ AP Extreme
  hosts: all
  gather_facts: no
  tasks:
    - name: Kiểm tra kết nối SSH
      ping:

    - name: Kiểm tra phiên bản hệ điều hành
      command: "show version"
      register: version_output

    - name: Hiển thị phiên bản hệ điều hành
      debug:
        var: version_output.stdout
