---
- name: Kiểm tra kết nối tới AP Extreme qua SSH
  hosts: all
  gather_facts: no
  tasks:
    - name: Kiểm tra kết nối qua lệnh ping
      ping:

    - name: Kiểm tra phiên bản hệ điều hành
      ios_command:
        commands:
          - show version
      register: version_output

    - name: Hiển thị phiên bản hệ điều hành
      debug:
        var: version_output
